### ISSUE TITLE
Create conda / pipenv environment for all tutorials

### ISSUE THREAD

**Issue by IsakFalk** [mlss-2019/tutorials#2]
It'd probably be a good idea to create a conda / pipenv environment file containing all of the necessary packages (https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html / https://docs.pipenv.org/en/latest/). 

This way all participants can create an MLSS2019 environment before coming to the actual summer school and it should work with all tutorials, reducing time spent on helping people setting things up.

I'm going through the notebooks and keeping a list of modules (not included in the standard Python library) used:
- scipy
- numpy
- matplotlib
- pystan
- gpflow
- tensorflow

**Comment by IsakFalk** [comment]
I'll take this on!

In the future, I'd need some people on OSX and Windows to make sure everything runs (I use Linux and can't really test on these platforms). Does anyone use a mac / windows machine and would like to volunteer?

**Comment by Kaixhin** [comment]
I have a Mac (and possibly Windows) so if you're able to get a working setup on Linux then let me know and I'll look into it.

**Comment by IsakFalk** [comment]
@Kaixhin Thanks man!
