### ISSUE TITLE
Hensman / GP: tutorial broken import

### ISSUE THREAD

**Issue by IsakFalk** [mlss-2019/tutorials#3]
In some of the notebooks, for example notebook 2, `matplotlib.pyplot` is imported using

```python
import matplotlib
plt = matplotlib.pyplot
```
which gives me and error
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-e9354e1550ca> in <module>
      1 import matplotlib
----> 2 plt = matplotlib.pyplot

AttributeError: module 'matplotlib' has no attribute 'pyplot'
```
.

I'm running a kernel using python3 and with matplotlib installed. I can import it using `import matplotlib.pyplot as plt` successfully.

The fix is simple, we can just change `plt = matplotlib.pyplot` to `import matplotlib.pyplot as plt` in all notebooks.

**Comment by IsakFalk** [comment]
Funny, I installed GPflow and now it works. Not sure why, but let's keep it like this for now.

**Comment by IsakFalk** [comment]
Actually, it doesn't work. If you run everything in the notebook when it's clean, you get errors. Should just change the imports as in 

> The fix is simple, we can just change `plt = matplotlib.pyplot` to `import matplotlib.pyplot as plt` in all notebooks.

**Comment by sanket-kamthe** [comment]
Fixed now
