### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by IsakFalk** [mlss-2019/tutorials#4]
This might not be a problem, maybe everyone is using python3. Anyhow, as the tutorials come in, we should keep track of what python version they are using so that we have the correct one ready at the start of the tutorials, alternatively change the needed syntax from python2 to python3 (mainly `print "output string"` to `print("output string")` and `xrange(n)` to `range(n)`).

Will come back to this as more tutorials come in.

**Comment by Kaixhin** [comment]
+1 for everyone keeping to Python 3 if possible.
