### ISSUE TITLE
Betancourt / MCMC: compute_mcmc_stats gives error

### ISSUE THREAD

**Issue by IsakFalk** [mlss-2019/tutorials#5]
I try to run the python files in the betancourt directory, but on file 2 and 3, when I run

```bash
python '2 - markov_chain_monte_carlo.py'
```
from the command line I get the error
```python
Traceback (most recent call last):
  File "2 - markov_chain_monte_carlo.py", line 143, in <module>
    compute_mcmc_stats([ s[0] for s in mcmc_samples[100:] ])
  File "2 - markov_chain_monte_carlo.py", line 58, in compute_mcmc_stats
    for s in [ 2 * i + 1 for i in range((L - 1) / 2) ]:
TypeError: 'float' object cannot be interpreted as an integer
```
which probably means that the term `(L - 1) / 2` becomes a `float` and the `range` operator needs the argument to be an `int`.

**Comment by sursu** [comment]
`[ 2 * i + 1 for i in range((L - 1) / 2) ]` just needs to be replaced with `np.array(1,L,2)`.

Similarly below:
`[ 2 * i + 3 for i in range((max_s - 2)/ 2) ]` should be replaced with `np.array(3,max_s+1,2)`.

Michael seems to have had a lot of fun writing those list comprehensions.
